remove input and add new arguments for the script

diff --git a/seperate-vm/drupal b/seperate-vm/drupal
--- a/seperate-vm/drupal
+++ b/seperate-vm/drupal
@@ -1,71 +1,64 @@
 #!/bin/bash
 
-getInput() {
-	local tmp_keycloak_base tmp_keycloak_realm
-	local confirm
+testInput() {
+	# TODO chekc all four variables are not empty and have valid formats
 
-	# Use environment variables if available
-	if [[ -n "$ENV_KEYCLOAK_BASE" && -n "$ENV_KEYCLOAK_REALM" ]]; then
-		KEYCLOAK_BASE="$ENV_KEYCLOAK_BASE"
-		KEYCLOAK_REALM="$ENV_KEYCLOAK_REALM"
-		echo "Using provided Keycloak configuration:"
-		echo "Keycloak Base URL     : $KEYCLOAK_BASE"
-		echo "Keycloak Realm        : $KEYCLOAK_REALM"
-		return 0
+	if [[ -z "$CLIENT_ID" ]]; then
+		echo "Error: CLIENT_ID is empty." >&2
+		return 1
 	fi
 
-	# Fall back to interactive input
-	while true; do
-		read -r -p "Enter Keycloak base url: " tmp_keycloak_base
-		read -r -p "Enter Keycloak realm: " tmp_keycloak_realm
-		echo
+	if [[ -z "$CLIENT_SECRET" ]]; then
+		echo "Error: CLIENT_SECRET is empty." >&2
+		return 1
+	fi
 
-		echo "Summary of entered information:"
-		echo "Keycloak Base URL     : $tmp_keycloak_base"
-		echo "Keycloak Realm        : $tmp_keycloak_realm"
-		echo
+	if [[ -z "$KEYCLOAK_BASE" ]]; then
+		echo "Error: KEYCLOAK_BASE is empty." >&2
+		return 1
+	fi
 
-		read -r -p "Is this information correct? (y/n): " confirm
-		if [[ "$confirm" =~ ^[Yy]$ ]]; then
-			KEYCLOAK_BASE="$tmp_keycloak_base"
-			KEYCLOAK_REALM="$tmp_keycloak_realm"
-			echo "Confirmed. Continuing..."
-			break
-		else
-			echo "Trying again..."
-			echo
-		fi
-	done
-	return 0
+	if [[ -z "$KEYCLOAK_REALM" ]]; then
+		echo "Error: KEYCLOAK_REALM is empty." >&2
+		return 1
+	fi
+}
+
+userCreate() {
+	chmod +x /var/www/html/vendor/bin/drush
+	/var/www/html/vendor/bin/drush user-create ${DRUPAL_USER} --mail="testmail@gmail.com" --password=${DRUPAL_USER_PASSWORD}
+	/var/www/html/vendor/bin/drush user-add-role "administrator" ${DRUPAL_USER}
+	## run as non root
+}
+
+moduleInstall() {
+	#TODO cehck if moduels already installed
+	composer require drupal/openid_connect drupal/keycloak
+	#TODO check if moduels already enabled
+	/var/www/html/vendor/bash/drush en keycloak -y
+	/var/www/html/vendor/bash/drush en openid_connect -y
+	/var/www/html/vendor/bash/drush cr
 }
 
 createClient() {
-	echo "Configuring Drupal OpenID Connect..."
-
-	KEYCLOAK_BASE="${KEYCLOAK_BASE%/}"
-
-	chmod +x vendor/bin/drush
-	vendor/bin/drush config:set openid_connect.settings.keycloak enabled true -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.client_id '$CLIENT_ID' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.client_secret '$CLIENT_SECRET' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_base '$KEYCLOAK_BASE' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_realm '$KEYCLOAK_REALM' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.userinfo_update_email false -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.enabled false -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.claim_name groups -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.split_groups false -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.split_groups_limit '0' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.rules [] -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_sso true -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_sign_out true -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.check_session.enabled false -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.check_session.interval null -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.redirect_url '' -y
-	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_i18n_enabled false -y
-	echo 'Rebuilding Drupal cache...'
+	vendor/bin/drush config:set openid_connect.settings.keycloak enabled true -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.client_id "${CLIENT_ID}" -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.client_secret "${CLIENT_SECRET}" -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_base "${KEYCLOAK_BASE}" -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_realm "${KEYCLOAK_REALM}" -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.userinfo_update_email false -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.enabled false -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.claim_name groups -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.split_groups false -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.split_groups_limit '0' -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_groups.rules "[]" -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_sso true -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_sign_out true -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.check_session.enabled false -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.check_session.interval null -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.redirect_url '' -y && \ 
+	vendor/bin/drush config:set openid_connect.settings.keycloak settings.keycloak_i18n_enabled false -y && \ 
 	vendor/bin/drush cr
-	echo 'Final configuration:'
-	vendor/bin/drush config:get openid_connect.settings.keycloak
 
 	if [ $? -ne 0 ]; then
 		echo "Error: Failed during Drupal configuration." >&2
@@ -75,27 +68,39 @@ createClient() {
 	return 0
 }
 
+DRUPAL_USER=""
+DRUPAL_USER_PASSWORD=""
 KEYCLOAK_BASE=""
 KEYCLOAK_REALM=""
 CLIENT_ID=""
 CLIENT_SECRET=""
-# CONTAINER_NAME="openplc_container"
 
 main() {
 
-	if [[ "$1" == "-c" ]]; then
+	if [[ "$1" == "--client-id" ]]; then
 		CLIENT_ID="$2"
 		shift 2
 	fi
 
-	if [[ "$1" == "-s" ]]; then
+	if [[ "$1" == "--client-secret" ]]; then
 		CLIENT_SECRET="$2"
 		shift 2
 	fi
 
-	{
+	if [[ "$1" == "--base" ]]; then
+		KEYCLOAK_BASE="$2"
+		shift 2
+	fi
 
-		getInput &&
+	if [[ "$1" == "--realm" ]]; then
+		KEYCLOAK_REALM="$2"
+		shift 2
+	fi
+
+	{
+		testInput &&
+			userCreate &&
+			moduleInstall &&
 			createClient &&
 			echo
 		echo "::: Drupal OpenID Connect Setup Complete :::"
@@ -105,4 +110,4 @@ main() {
 	}
 }
 
-time main "$@"
+main "$@"
