save clients as json array & add keycloak path as input

diff --git a/seperate-vm/keycloak b/seperate-vm/keycloak
--- a/seperate-vm/keycloak
+++ b/seperate-vm/keycloak
@@ -16,14 +16,25 @@ checkInput() {
 		exit 1
 	fi
 
+	if jq -e --arg client_id "$KEYCLOAK_CLIENT_ID" 'any(.[]; .clientId == $client_id)' "$CLIENT_JSON_PATH" >/dev/null; then
+		echo "Error: Client ID '$KEYCLOAK_CLIENT_ID' already exists in $CLIENT_JSON_PATH." >&2
+		exit 1
+	fi
+
+	if [[ ! -f "$KEYCLOAK_PATH" ]]; then
+		echo "Error: File not found at '$KEYCLOAK_PATH'" >&2
+		exit 1
+	fi
+
 }
 
 getInput() {
-	local tmp_keycloak_realm tmp_keycloak_base tmp_keycloak_user tmp_keycloak_password tmp_keycloak_client_id tmp_drupal_base
+	local tmp_keycloak_path tmp_keycloak_realm tmp_keycloak_base tmp_keycloak_user tmp_keycloak_password tmp_keycloak_client_id tmp_drupal_base
 	local confirm
 
 	while true; do
 		echo "!! Kindly use lowercase for naming and don't include white spaces !!"
+		read -r -p "Enter Keycloak kcadm path(Eg /opt/keycloak/bin/kcadm.sh): " tmp_keycloak_path
 		read -r -p "Enter Keycloak realm: " tmp_keycloak_realm
 		read -r -p "Enter Keycloak base url : " tmp_keycloak_base
 		read -r -p "Enter Keycloak admin user: " tmp_keycloak_user
@@ -34,6 +45,7 @@ getInput() {
 		echo
 
 		echo "Summary of entered information:"
+		echo "Keycloak kcadm Path  : $tmp_keycloak_path"
 		echo "Keycloak Realm        : $tmp_keycloak_realm"
 		echo "Keycloak Base URL     : $tmp_keycloak_base"
 		echo "Keycloak Admin User   : $tmp_keycloak_user"
@@ -43,6 +55,7 @@ getInput() {
 
 		read -r -p "Is this information correct? (y/n): " confirm
 		if [[ "$confirm" =~ ^[Yy]$ ]]; then
+			KEYCLOAK_PATH="$tmp_keycloak_path"
 			KEYCLOAK_REALM="$tmp_keycloak_realm"
 			KEYCLOAK_BASE="$tmp_keycloak_base"
 			KEYCLOAK_USER="$tmp_keycloak_user"
@@ -62,17 +75,30 @@ getInput() {
 	return 0
 }
 
-updateClientJSON() {
-	jq --arg client_id "$KEYCLOAK_CLIENT_ID" \
-		--arg redirect_uri "$DRUPAL_BASE/openid-connect/keycloak" \
-		'.clientId = $client_id | .redirectUris = [$redirect_uri]' "$CLIENT_JSON_PATH" >tmp && mv tmp "$CLIENT_JSON_PATH"
+createTempJSON() {
+	echo "Creating temp client json file tmp_client.json..."
+	local redirect_uri="${DRUPAL_BASE%/}/openid-connect/keycloak"
+	cat >tmp_client.json <<EOF
+{
+    "clientId": "$KEYCLOAK_CLIENT_ID",
+    "enabled": true,
+	"publicClient": false,
+    "protocol": "openid-connect",
+	"clientAuthenticatorType": "client-secret",
+	"standardFlowEnabled": true,
+    "redirectUris": [
+        "$redirect_uri"
+    ]
+}
+EOF
 
 	if [ $? -ne 0 ]; then
-		echo "Error: Failed to update $CLIENT_JSON_PATH." >&2
+		echo "Error: Failed to create temp_client.json." >&2
 		return 1
 	fi
-	echo "$CLIENT_JSON_PATH updated with Client ID and Redirect URI."
+	echo "temp_client.json created successfully."
 	return 0
+
 }
 
 updateConfigJSON() {
@@ -105,7 +131,7 @@ updateConfigJSON() {
 
 createClient() {
 	echo "Keycloak login"
-	sudo -u keycloak /opt/keycloak/bin/kcadm.sh config credentials \
+	sudo -u keycloak "$KEYCLOAK_PATH" config credentials \
 		--server "$KEYCLOAK_BASE" \
 		--realm "$KEYCLOAK_REALM" \
 		--user "$KEYCLOAK_USER" \
@@ -113,31 +139,45 @@ createClient() {
 
 	if [ $? -ne 0 ]; then
 		echo "Error: Failed to login. Check server URL, realm, user, or password." >&2
+		rm -f tmp_client.json
 		return 1
 	fi
 	echo "Logged in successfully."
 
 	echo "Creating Keycloak client '$KEYCLOAK_CLIENT_ID'..."
-	sudo -u keycloak /opt/keycloak/bin/kcadm.sh create clients -r "$KEYCLOAK_REALM" -f "$CLIENT_JSON_PATH"
+	sudo -u keycloak "$KEYCLOAK_PATH" create clients -r "$KEYCLOAK_REALM" -f tmp_client.json
 
 	if [ $? -ne 0 ]; then
 		echo "Error: Failed to create Keycloak client." >&2
+		rm -f tmp_client.json
 		return 1
 	fi
 	echo "Keycloak client '$KEYCLOAK_CLIENT_ID' created."
 
-	echo "Retrieving client details and saving to secret.json..."
-	sudo -u keycloak /opt/keycloak/bin/kcadm.sh get clients -r "$KEYCLOAK_REALM" -q clientId="$KEYCLOAK_CLIENT_ID" --fields clientId,secret >secret.json
+	local secret
+
+	echo "Retrieving client details and saving to client.json..."
+	secret=$(sudo -u keycloak "$KEYCLOAK_PATH" get clients -r "$KEYCLOAK_REALM" -q clientId="$KEYCLOAK_CLIENT_ID" --fields secret | jq -r '.[0].secret')
+
+	echo "Adding client details to client.json..."
+	jq --arg secret "$secret" \
+		--slurpfile temp_client tmp_client.json \
+		'. += [$temp_client[0] | {clientId: .clientId, secret: $secret} +
+		(. | del(.clientId))]' "$CLIENT_JSON_PATH" >tmp && mv tmp "$CLIENT_JSON_PATH"
 
 	if [ $? -ne 0 ]; then
-		echo "Warning: Could not retrieve client details" >&2
-	else
-		echo "Client details saved to secret.json"
+		echo "Error: Failed to update $CLIENT_JSON_PATH." >&2
+		rm -f tmp_client.json
+		return 1
 	fi
+
+	echo "Client details saved to client.json"
+	rm -f tmp_client.json
 
 	return 0
 }
 
+KEYCLOAK_PATH=""
 KEYCLOAK_REALM=""
 KEYCLOAK_BASE=""
 KEYCLOAK_USER=""
@@ -153,6 +193,12 @@ main() {
 		exit 1
 	fi
 
+	touch "$CLIENT_JSON_PATH"
+	if [ ! -s "$CLIENT_JSON_PATH" ]; then
+		echo "Initializing empty $CLIENT_JSON_PATH..."
+		echo "[]" >"$CLIENT_JSON_PATH"
+	fi
+
 	if [[ ! -f "$CLIENT_JSON_PATH" ]]; then
 		echo "Error: Client configuration file '$CLIENT_JSON_PATH' not found." >&2
 		exit 1
@@ -165,12 +211,13 @@ main() {
 
 	{
 		getInput &&
-			updateClientJSON &&
+			createTempJSON &&
 			updateConfigJSON &&
 			createClient &&
 			echo "::: Keycloak Client Setup Complete :::"
 	} || {
 		echo "!!! Keycloak Client Setup Failed !!!"
+		rm -f tmp_client.json
 	}
 }
 
